version: '2'

services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
  web:
      build: apache-php
      container_name: apache-php
      environment:
      ENV http_proxy http://10.254.0.18:81
      ENV https_proxy http://10.254.0.18:81
      depends_on:
      - mariadb
      volumes:
      - /opt/docker/www/:/usr/local/apache2/htdocs
      ports:
      - "80:80"
      - "443:443"
    