version: '3.1'
services:
        db:
         image: mariadb
         restart: always
         environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_USER: admin
         MYSQL_PASSWORD: test
         MYSQL_DATABASE: database
         ports:
         - "8889:3306"
        volumes:
       - /opt/docker/db:/var/lib/mysql

        web:
         build: apache-php
         container_name: apache-php
         depends_on:
          - db
         volumes:
          - /opt/docker/www/:/usr/local/apache2/htdocs
         ports:
          - "80:80"
          - "443:443"