version: '3.1'
services:
        db:
         build: mariadb-server
         container_name: mariadb-server
         ports:
          - "9906:3306"
         volumes:
          - /opt/docker/aleskratochvil/mysql/var/lib/mysql:/var/lib/mysql

        web:
         build: apache-php
         container_name: apache-php
         depends_on:
          - db
         volumes:
          - /opt/docker/aleskratochvil/www/:/usr/local/apache2/htdocs
         ports:
          - "80:80"
          - "443:443"